"""Initial schema with dialogues, conversations, and fine_tuning_jobs tables

Revision ID: c84d4449d11f
Revises:
Create Date: 2025-12-26 17:59:59.579039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision = 'c84d4449d11f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('ai_concept', sa.String(length=50), nullable=False),
    sa.Column('user_input', sa.Text(), nullable=False),
    sa.Column('ai_response', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('thinking_process', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retrieved_dialogues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('agent_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_ai_concept'), ['ai_concept'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_session_id'), ['session_id'], unique=False)

    op.create_table('dialogues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comedian', sa.String(length=50), nullable=False),
    sa.Column('movie_name', sa.String(length=200), nullable=False),
    sa.Column('character_name', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('dialogue_text', sa.Text(), nullable=False),
    sa.Column('dialogue_tamil', sa.Text(), nullable=True),
    sa.Column('dialogue_english', sa.Text(), nullable=True),
    sa.Column('dialogue_tanglish', sa.Text(), nullable=True),
    sa.Column('scene_description', sa.Text(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('emotion', sa.String(length=50), nullable=True),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dialogues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dialogues_comedian'), ['comedian'], unique=False)
        batch_op.create_index(batch_op.f('ix_dialogues_emotion'), ['emotion'], unique=False)
        batch_op.create_index(batch_op.f('ix_dialogues_movie_name'), ['movie_name'], unique=False)

    op.create_table('fine_tuning_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=200), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('base_model', sa.String(length=100), nullable=True),
    sa.Column('fine_tuned_model', sa.String(length=200), nullable=True),
    sa.Column('training_file_path', sa.Text(), nullable=True),
    sa.Column('training_samples', sa.Integer(), nullable=True),
    sa.Column('hyperparameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fine_tuning_jobs')
    with op.batch_alter_table('dialogues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dialogues_movie_name'))
        batch_op.drop_index(batch_op.f('ix_dialogues_emotion'))
        batch_op.drop_index(batch_op.f('ix_dialogues_comedian'))

    op.drop_table('dialogues')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_session_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_created_at'))
        batch_op.drop_index(batch_op.f('ix_conversations_ai_concept'))

    op.drop_table('conversations')
    # ### end Alembic commands ###
