"""Simplify schema - remove movie_name, character_name, year, dialogue_tamil, dialogue_text, scene_description, extra_metadata, updated_at

Revision ID: df823f4e0b27
Revises: c84d4449d11f
Create Date: 2025-12-26 22:05:55.046748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'df823f4e0b27'
down_revision = 'c84d4449d11f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dialogues', schema=None) as batch_op:
        batch_op.alter_column('dialogue_english',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_dialogues_movie_name'))
        batch_op.drop_column('dialogue_text')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('scene_description')
        batch_op.drop_column('character_name')
        batch_op.drop_column('dialogue_tamil')
        batch_op.drop_column('extra_metadata')
        batch_op.drop_column('year')
        batch_op.drop_column('movie_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dialogues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movie_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dialogue_tamil', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('character_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('scene_description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dialogue_text', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.create_index(batch_op.f('ix_dialogues_movie_name'), ['movie_name'], unique=False)
        batch_op.alter_column('dialogue_english',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
